### PR TITLE
Fix refresh of LineSegmentShapeNode

### LINKED ISSUE #1380: Setting DataVariance=DYNAMIC causes simulation to slow and then stop
A explained in the forum [here](https://dartsim.discourse.group/t/setting-datavariance-dynamic-causes-simulation-to-slow-and-then-stop/95/3). Setting dataVariance to DYNAMIC or DYNAMIC_ELEMENTS causes the simulation to slow and then stop after approximately 10 seconds.

In the forum Grey explains the problem as..

It seems that [this line](https://github.com/dartsim/dart/blob/d8f2636cc3d36430b5de65405b0b13c136485f94/dart/gui/osg/render/LineSegmentShapeNode.cpp#L221) is likely the culprit, because it’s adding a primitive set without removing the previous one. So the set of line segments that need to be drawn get piled up on top of each other instead of having the new set replace the old set.

### PR DESCRIPTION
**Pull request by jslee02**
`LineSegmentShapeNode` keeps adding new line segments instead of refreshing with new line. See the details in #1380 and [this post](https://dartsim.discourse.group/t/setting-datavariance-dynamic-causes-simulation-to-slow-and-then-stop/95).

Resolves #1380.

***

**Before creating a pull request**

- [x] Document new methods and classes
- [x] Format new code files using `clang-format`

**Before merging a pull request**

- [x] Set version target by selecting a milestone on the right side
- [x] Summarize this change in `CHANGELOG.md`
- [x] Add unit test(s) for this change (N/A)

### CODE REVIEW

File: dart/gui/osg/render/LineSegmentShapeNode.cpp [hunk 1]
```diff
@@ -207,18 +210,16 @@ void LineSegmentShapeDrawable::refresh(bool firstTime)
     const common::aligned_vector<Eigen::Vector2i>& connections
         = mLineSegmentShape->getConnections();
 
-    ::osg::ref_ptr<::osg::DrawElementsUInt> elements
-        = new ::osg::DrawElementsUInt(::osg::PrimitiveSet::LINES);
-    elements->reserve(2 * connections.size());
+    mElements->resize(2 * connections.size());
```
Comment (mxgrey) [inline dart/gui/osg/render/LineSegmentShapeNode.cpp]: I don't think we want to use `resize(~)` alongside `push_back(~)`, because that means we're going to make `mElements` the size `2 * connections.size()` and then later push back an additional `2 * connections.size()` number of new elements.

I would recommend using `reserve(2 * connections.size()` and then `clear()`.

Comment (mxgrey) [reply dart/gui/osg/render/LineSegmentShapeNode.cpp]: Alternatively `resize(~)` and then `[2*i] = ` and `[2*i+1] = ` would also work, but that feels more risky to me.

Comment (jslee02) [reply dart/gui/osg/render/LineSegmentShapeNode.cpp]: Thanks for catching this out. Let me fix this as suggested.

**Comment by jslee02** [comment]
It was an easy fix! Thanks for the review.
