### PR TITLE
Fix incorrect LCP construction in JointConstraint for multi-DOFs joints (#1596)

### LINKED ISSUE #1596: Gazebo crashes when universal joints reach limits since 6.11.0
### Bug Report
- [X] I checked the [documentation](http://dartsim.github.io/) and the [forum](https://dartsim.discourse.group/) but found no answer.
- [X] I checked to make sure that this issue has not already been filed.

#### Environment
* DART version: 6.11.0
* OS name and version name(or number): macOS Catalina
* Compiler name and version number: Apple clang version 12.0.0 (clang-1200.0.32.29)

#### Expected Behavior

There are tests in gazebo that push the Universal joints to to their position limits in gazebo, both `INTEGRATION_joint_universal` and some sub-tests of `INTEGRATION_joint_spawn`. These tests were passing as recently as July 22nd:

* https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/79/
* https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/79/testReport/(root)/TestRuns_JointSpawningTest_All/SpawnJointTypes_27/
* https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/79/testReport/(root)/PhysicsEngines_JointTestUniversal/Limits_3/

#### Current Behavior

The mentioned CI job is not run daily. The next time it was run on July 30th, the universal joint tests involving limits began crashing with an `ODE INTERNAL ERROR`:

~~~
ODE INTERNAL ERROR 1: assertion "lo[k] <= 0 && hi[k] >= 0" failed in dSolveLCP() [/tmp/dartsim-20210728-75371-6nj383/dart-6.11.0/dart/external/odelcpsolver/lcp.cpp:791]
~~~

* https://build.osrfoundation.org/job/gazebo-ci-gazebo11-homebrew-amd64/80/

Console output from failure in `INTEGRATION_joint_universal`: <details>
~~~
233: [ RUN      ] PhysicsEngines/JointTestUniversal.Limits/3
233: [Msg] Waiting for master.
233: [Msg] Connected to gazebo master @ http://127.0.0.1:11345
233: [Msg] Publicized address: 172.23.1.206
233: [Msg] Loading world file [/Users/jenkins/workspace/gazebo-ci-gazebo11-homebrew-amd64/gazebo/test/worlds/universal_joint_test.world]
233: [Wrn] [DARTPhysics.cc:98] Gravity vector is (0, 0, 0). Objects will float.
233: [Dbg] [DARTModel.cc:72] Initializing DART model model_1
233: [Dbg] [DARTModel.cc:166] Building DART BodyNode for link 'link_00' and joint 'joint_00'.
233: [Dbg] [DARTModel.cc:166] Building DART BodyNode for link 'link_01' and joint 'joint_01'.
233: [Err] [DARTJoint.cc:195] DARTJoint: SetAnchor is not implemented.
233: [Dbg] [ServerFixture.cc:211] ServerFixture load in 0.6 seconds, timeout after 600 seconds
233: [Dbg] [joint_universal.cc:133] Setting gravity gx 5 gy 5 pose 1e-06 1e-06 1 0.452501 -0.471958 -0.217518
233: /Users/jenkins/workspace/gazebo-ci-gazebo11-homebrew-amd64/gazebo/test/integration/joint_universal.cc:141: Failure
233: The difference between des1 and jointLower->Position(1) is 0.21621770000094703, which exceeds 1e-2, where
233: des1 evaluates to -0.29999999999999999,
233: jointLower->Position(1) evaluates to -0.51621770000094702, and
233: 1e-2 evaluates to 0.01.
233: /Users/jenkins/workspace/gazebo-ci-gazebo11-homebrew-amd64/gazebo/test/integration/joint_universal.cc:145: Failure
233: The difference between des0 and eulerAngles.X() is 0.052500520896339997, which exceeds 0.05, where
233: des0 evaluates to 0.40000000000000002,
233: eulerAngles.X() evaluates to 0.45250052089634002, and
233: 0.05 evaluates to 0.050000000000000003.
233: /Users/jenkins/workspace/gazebo-ci-gazebo11-homebrew-amd64/gazebo/test/integration/joint_universal.cc:146: Failure
233: The difference between des1 and eulerAngles.Y() is 0.17195796755424692, which exceeds 0.05, where
233: des1 evaluates to -0.29999999999999999,
233: eulerAngles.Y() evaluates to -0.4719579675542469, and
233: 0.05 evaluates to 0.050000000000000003.
233: 
233: ODE INTERNAL ERROR 1: assertion "lo[k] <= 0 && hi[k] >= 0" failed in dSolveLCP() [/tmp/dartsim-20210728-82012-bfecll/dart-6.11.0/dart/external/odelcpsolver/lcp.cpp:791]
233/416 Test #233: INTEGRATION_joint_universal ...........................Subprocess aborted***Exception:  12.17 sec
~~~
</details>

Console output from failure in `INTEGRATION_joint_spawn`: <details>
~~~
229: [ RUN      ] TestRuns/JointSpawningTest_All.SpawnJointTypes/27
229: [Dbg] [joint_test.hh:69] Params: (0x10b44fe98 pointing to "dart", 0x10b44fa21 pointing to "universal")
229: [Msg] Waiting for master.
229: [Msg] Connected to gazebo master @ http://127.0.0.1:11345
229: [Msg] Publicized address: 172.23.1.206
229: [Msg] Loading world file [/Users/jenkins/workspace/gazebo-ci-gazebo11-homebrew-amd64/gazebo/worlds/empty.world]
229: [Dbg] [DARTModel.cc:72] Initializing DART model ground_plane
229: [Dbg] [DARTModel.cc:128] Building DART BodyNode for link 'link' with a free joint.
229: Warning [BodyNode.cpp:498] [BodyNode] A negative or zero mass [0] is set to BodyNode [link], which can cause invalid physical behavior or segfault. Consider setting positive value instead.
229: [Dbg] [ServerFixture.cc:211] ServerFixture load in 0.5 seconds, timeout after 600 seconds
229: [Dbg] [joint_spawn.cc:88] SpawnJoint universal child parent
229: [Dbg] [DARTModel.cc:72] Initializing DART model joint_model0
229: [Dbg] [DARTModel.cc:128] Building DART BodyNode for link 'parent' with a free joint.
229: [Dbg] [DARTModel.cc:166] Building DART BodyNode for link 'child' and joint 'joint'.
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Wrn] [DARTPhysics.cc:491] Not implemented yet in DART.
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:485] DARTLink::SetAngularVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: [Dbg] [DARTLink.cc:414] DARTLink::SetLinearVel() doesn't make sense if the parent joint is not free joint (6-dof).
229: 
229: ODE INTERNAL ERROR 1: assertion "lo[k] <= 0 && hi[k] >= 0" failed in dSolveLCP() [/tmp/dartsim-20210728-82012-bfecll/dart-6.11.0/dart/external/odelcpsolver/lcp.cpp:791]
229/416 Test #229: INTEGRATION_joint_spawn ...............................Subprocess aborted***Exception:  92.28 sec
~~~
</details>

I believe this was triggered by the merge of dartsim 6.11.0 into homebrew-core in https://github.com/Homebrew/homebrew-core/pull/82071 on July 28th. Having looked at the changelog, I believe it is related to #1587.

#### Steps to Reproduce

1. `brew install gazebo11` on macOS
2. Download gazebo's [test/worlds/universal_joint_test.world](https://github.com/osrf/gazebo/raw/gazebo11/test/worlds/universal_joint_test.world) to a local folder. This would contains a two-link system with two universal joints, one of which is connected to the `world`.
3. Open the test world with dart: `gazebo --verbose -e dart path/to/test/worlds/universal_joint_test.world`
4. Set the `x` or `y` component of gravity to a non-zero value, such as `1`. This causes the pendulum to swing towards its joint limits and then crash.

#### Code to Reproduce

See the [Limits test in joint_universal.cc](https://github.com/osrf/gazebo/blob/b502f17729302fa0da8e2a00ffbd69112bb7e6aa/test/integration/joint_universal.cc#L49-L148).

### PR DESCRIPTION
**Pull request by jslee02**
* Fix incorrect LCP construction in `JointConstraint` for multi-DOFs joints (fixes #1596)
* Add `universal` joint type in `SDFParser`
* Encode visual/collision name attribute of SDF in ShapeNode name
* Bump version to 6.11.1

***

**Before creating a pull request**

- [x] Document new methods and classes
- [x] Format new code files using `clang-format`

**Before merging a pull request**

- [x] Set version target by selecting a milestone on the right side
- [x] Summarize this change in `CHANGELOG.md`
- [x] Add unit test(s) for this change

### CODE REVIEW

File: dart/constraint/JointConstraint.cpp [hunk 1]
```diff
@@ -400,14 +400,33 @@ void JointConstraint::getInformation(ConstraintInfo* lcp)
   const int dof = static_cast<int>(mJoint->getNumDofs());
   for (int i = 0; i < dof; ++i)
   {
-    assert(lcp->w[index] == 0.0);
+    if (!mActive[i])
+      continue;
```
Comment (jslee02) [inline dart/constraint/JointConstraint.cpp:404]: These two lines are the actual fix for #1596. Without these lines, this function attempted to access invalid indices of the arrays in `lcp`.

Comment (scpeters) [reply dart/constraint/JointConstraint.cpp:404]: 👍

**Comment by scpeters** [comment]
Thanks for the incredibly quick fix and adding the test over. I would make one small adjustment to the test, since I tried reverting the two lines that fix the bug, and the test currently passes without the fix. I've widened the joint limits a bit in the following patch, which I think is an improvement because it makes the test fail on my machine without the fix, while it still passes with the fix:

~~~
diff --git a/data/sdf/test/test_issue1596.model b/data/sdf/test/test_issue1596.model
index 793b8467f7..ee7342057b 100644
--- a/data/sdf/test/test_issue1596.model
+++ b/data/sdf/test/test_issue1596.model
@@ -124,8 +124,8 @@
       <axis>
         <xyz>1 0 0</xyz>
         <limit>
-          <lower>-0.1</lower>
-          <upper>0.1</upper>
+          <lower>-1.2</lower>
+          <upper>1.2</upper>
           <stiffness>1e6</stiffness>
         </limit>
         <dynamics>
@@ -135,8 +135,8 @@
       <axis2>
         <xyz>0 1 0</xyz>
         <limit>
-          <lower>-0.1</lower>
-          <upper>0.1</upper>
+          <lower>-1.2</lower>
+          <upper>1.2</upper>
           <stiffness>1e6</stiffness>
         </limit>
         <dynamics>
@@ -155,8 +155,8 @@
       <axis>
         <xyz>1 0 0</xyz>
         <limit>
-          <lower>-0.1</lower>
-          <upper>0.1</upper>
+          <lower>-1.2</lower>
+          <upper>1.2</upper>
         </limit>
         <dynamics>
           <damping>0.1</damping>
@@ -165,8 +165,8 @@
       <axis2>
         <xyz>0 1 0</xyz>
         <limit>
-          <lower>-0.1</lower>
-          <upper>0.1</upper>
+          <lower>-1.2</lower>
+          <upper>1.2</upper>
         </limit>
         <dynamics>
           <damping>0.1</damping>
~~~

**Comment by jslee02** [comment]
Interesting, it was the opposite in my case. Narrowing the limits made the difference. I guess it's possible that the gravity I used (i.e., [1, 1, 0]) was different from the one in your test. Using [9.81, 9.81, 0] showed the same results as yours with the widen limits.

**Review by scpeters — APPROVED** [review]
I left comments about two asserts, but I leave judgment about them in your hands

aside from that, everything looks great to me, so I will mark this as approved

I can re-review if you decide to make further changes

File: dart/utils/sdf/SdfParser.cpp [hunk 2]
```diff
@@ -1028,10 +1028,12 @@ void readVisualizationShapeNode(
     const common::Uri& baseUri,
     const common::ResourceRetrieverPtr& retriever)
 {
+  assert(hasAttribute(vizShapeNodeEle, "name"));
```
[the remark this answers is not in the document]
Comment (jslee02) [reply dart/utils/sdf/SdfParser.cpp]: Good call! Changed to print warning and use default name when the name attribute is missing since DART currently doesn't use exceptions for error handling.

**Review by scpeters — APPROVED** [review]
